# fornax.gdb — GDB helpers for Fornax kernel debugging via QEMU
#
# Usage:
#   Terminal 1:  make debug-smp        (or: make debug, debug-dev, etc.)
#   Terminal 2:  gdb -x fornax.gdb
#
# The kernel runs immediately with --debug. Use --debug-wait (via Makefile
# passing -S to QEMU) if you need to catch early boot.
#
# First-time setup:
#   1. Let the kernel boot to a shell prompt (serial output in terminal 1)
#   2. In GDB (terminal 2), press Ctrl+C to break
#   3. Run: fornax-calibrate
#      This finds the UEFI relocation offset automatically.
#   4. Now all fornax-* commands work with correct addresses.
#
# Key QEMU/GDB features for SMP:
#   info threads          — list all vCPUs (one "thread" per core)
#   thread N              — switch to core N
#   thread apply all bt   — backtrace on ALL cores simultaneously
#   watch *0xADDR         — hardware watchpoint (catches who writes)
#   break func if cond    — conditional breakpoint
#   set scheduler-locking on  — freeze other cores while stepping

set confirm off
set pagination off
set architecture i386:x86-64
set disassembly-flavor intel

# Connect to QEMU GDB stub
target remote :1234

# ── Load auto-generated symbol addresses from PDB ────────────────────
# Generated by: ./scripts/gen-gdb-syms.sh (run automatically by make debug*)
# Contains $fn_<name> for functions, $d_<name> for data, $koff for offset.
source fornax-syms.gdb

# ── Constants ────────────────────────────────────────────────────────
set $MAX_PROCESSES = 128
set $MAX_CORES = 128

# ProcessState enum values (src/process.zig:80-87)
set $STATE_FREE = 0
set $STATE_RUNNING = 1
set $STATE_READY = 2
set $STATE_BLOCKED = 3
set $STATE_ZOMBIE = 4
set $STATE_DEAD = 5

# ── Struct layouts (from PDB type info) ──────────────────────────────
# Regenerate with: llvm-pdbutil dump --types ... | grep LF_FIELDLIST
#
# sizeof(Process) = 18816
# Key Process field offsets:
#   pid:            14612 (u32)
#   state:          18801 (u8 enum)
#   assigned_core:  18781 (u8)
#   core_affinity:  18776 (i16)
#   user_rip:       40    (u64)
#   user_rsp:       48    (u64)
#   name:           18783 (16 bytes)
#   container_id:   18799 (u8)
#   parent_pid:     14624 (optional u32)
#   vt:             18780 (u8)
#   uid:            18772 (u16)
set $PROC_SIZE = 18816
set $PROC_PID = 14612
set $PROC_STATE = 18801
set $PROC_CORE = 18781
set $PROC_AFFINITY = 18776
set $PROC_USER_RIP = 40
set $PROC_USER_RSP = 48
set $PROC_NAME = 18783
set $PROC_VT = 18780
set $PROC_UID = 18772
set $PROC_PARENT = 14624

# sizeof(PerCpu) = 200
# PerCpu field offsets (Zig reordered for alignment):
#   current:          0   (?*anyopaque = u64)
#   idle_ticks:       8   (u64)
#   ctx_switches:     16  (u64)
#   syscalls:         24  (u64)
#   interrupts:       32  (u64)
#   run_queue:        40  (RunQueue, 152 bytes)
#   core_id:          192 (u8)
#   ipi_pending:      193 (u8)
#   tlb_flush_pending:194 (bool)
#   online:           195 (bool)
#   in_fault_recovery:196 (bool)
set $PERCPU_SIZE = 200
set $PC_CURRENT = 0
set $PC_IDLE = 8
set $PC_CTX_SW = 16
set $PC_SYSCALLS = 24
set $PC_INTERRUPTS = 32
set $PC_RUN_QUEUE = 40
set $PC_CORE_ID = 192
set $PC_IPI = 193
set $PC_TLB_FLUSH = 194
set $PC_ONLINE = 195

# sizeof(RunQueue) = 152
# RunQueue field offsets (Zig reordered):
#   head:     0  (u32)
#   tail:     4  (u32)
#   len:      8  (u32)
#   lock:     12 (SpinLock, 12 bytes)
#   entries:  24 (u16[64] = 128 bytes)
set $RQ_HEAD = 0
set $RQ_TAIL = 4
set $RQ_LEN = 8
set $RQ_LOCK = 12
set $RQ_ENTRIES = 24

# sizeof(SpinLock) = 12
#   next:    0 (u32)
#   serving: 4 (u32)
#   owner:   8 (i8)
set $SL_NEXT = 0
set $SL_SERVING = 4
set $SL_OWNER = 8

# ── Helper commands ──────────────────────────────────────────────────

define fornax-help
  printf "Fornax GDB commands:\n"
  printf "\n"
  printf "  Setup:\n"
  printf "    fornax-calibrate    Auto-detect UEFI kernel relocation offset\n"
  printf "    fornax-offset ADDR  Manually set kernel offset\n"
  printf "\n"
  printf "  Inspection:\n"
  printf "    fornax-cores        Show all online cores + current process\n"
  printf "    fornax-procs        List all non-free processes\n"
  printf "    fornax-proc PID     Show detailed info for a process\n"
  printf "    fornax-runq         Show per-core run queue contents\n"
  printf "    fornax-locks        Check spinlocks for contention\n"
  printf "    fornax-bt-all       Backtrace on all vCPUs\n"
  printf "    fornax-gs           Show per-CPU AsmState\n"
  printf "\n"
  printf "  Breakpoints:\n"
  printf "    fornax-bp $fn_NAME  Set breakpoint on kernel function\n"
  printf "    fornax-watch ADDR   Set hardware write watchpoint\n"
  printf "    fornax-disas $fn_N  Disassemble a kernel function\n"
  printf "\n"
  printf "  Examples:\n"
  printf "    fornax-bp $fn_markReady             Break on markReady()\n"
  printf "    fornax-bp $fn_scheduleNext          Break on scheduleNext()\n"
  printf "    fornax-bp $fn_sendToServer          Break on sendToServer()\n"
  printf "    watch *(int*)($d_table_lock+$koff)  Watch table_lock.next\n"
  printf "    fornax-disas $fn_switchTo            Disassemble switchTo\n"
  printf "\n"
  printf "  Standard GDB for SMP:\n"
  printf "    info threads                  List all vCPUs\n"
  printf "    thread N                      Switch to core N\n"
  printf "    thread apply all bt           Backtrace on all cores\n"
  printf "    set scheduler-locking on      Freeze other cores while stepping\n"
  printf "    set scheduler-locking off     Let all cores run (default)\n"
end

# ── Calibration ──────────────────────────────────────────────────────

define fornax-calibrate
  printf "Searching for PE header (MZ signature) in first 512 MB...\n"
  find /b 0x100000, 0x20000000, 0x4d, 0x5a
  printf "\nIf addresses were found above, look for one near the start of RAM.\n"
  printf "OVMF typically loads the kernel around 0x6000000-0x7000000.\n"
  printf "Verify with: x/2bx <addr>  (should show 4d 5a = MZ)\n"
  printf "\nThen set: fornax-offset <addr>\n"
end

define fornax-offset
  if $argc != 1
    printf "Usage: fornax-offset 0xADDRESS\n"
    printf "  Set the UEFI kernel relocation offset.\n"
  else
    set $koff = $arg0
    printf "Kernel offset set to 0x%lx\n", $koff
    printf "  markReady   @ 0x%lx\n", ($fn_markReady + $koff)
    printf "  switchTo    @ 0x%lx\n", ($fn_switchTo + $koff)
    printf "  processes[] @ 0x%lx\n", ($d_processes + $koff)
    printf "  percpu[]    @ 0x%lx\n", ($d_percpu_array + $koff)
  end
end

# ── Per-CPU inspection ───────────────────────────────────────────────

define fornax-cores
  if $koff == 0
    printf "Warning: $koff not set. Run fornax-calibrate first.\n"
  end
  printf "Core  PID    State     CtxSw   Syscalls  Interrupts\n"
  printf "----  -----  --------  ------  --------  ----------\n"
  set $i = 0
  while $i < $MAX_CORES
    set $base = ($d_percpu_array + $koff) + ($i * $PERCPU_SIZE)
    set $online = *(unsigned char*)($base + $PC_ONLINE)
    if $online
      set $core_id = *(unsigned char*)($base + $PC_CORE_ID)
      set $cur_ptr = *(unsigned long long*)($base + $PC_CURRENT)
      set $ctx = *(unsigned long long*)($base + $PC_CTX_SW)
      set $sys = *(unsigned long long*)($base + $PC_SYSCALLS)
      set $irq = *(unsigned long long*)($base + $PC_INTERRUPTS)
      if $cur_ptr != 0
        set $pid = *(unsigned int*)($cur_ptr + $PROC_PID)
        set $st = *(unsigned char*)($cur_ptr + $PROC_STATE)
        set $sn = "?"
        if $st == 0
          set $sn = "free"
        end
        if $st == 1
          set $sn = "running"
        end
        if $st == 2
          set $sn = "ready"
        end
        if $st == 3
          set $sn = "blocked"
        end
        if $st == 4
          set $sn = "zombie"
        end
        if $st == 5
          set $sn = "dead"
        end
        printf "  %2d  %5d  %-8s  %6llu  %8llu  %10llu\n", $core_id, $pid, $sn, $ctx, $sys, $irq
      else
        printf "  %2d  (idle) -         %6llu  %8llu  %10llu\n", $core_id, $ctx, $sys, $irq
      end
    end
    set $i = $i + 1
  end
end

# ── Process inspection ───────────────────────────────────────────────

define fornax-procs
  if $koff == 0
    printf "Warning: $koff not set. Run fornax-calibrate first.\n"
  end
  printf "PID   State     Core  VT  UID  Parent  User-RIP\n"
  printf "----  --------  ----  --  ---  ------  --------\n"
  set $i = 0
  while $i < $MAX_PROCESSES
    set $proc = ($d_processes + $koff) + ($i * $PROC_SIZE)
    set $st = *(unsigned char*)($proc + $PROC_STATE)
    if $st != $STATE_FREE
      set $pid = *(unsigned int*)($proc + $PROC_PID)
      set $core = *(unsigned char*)($proc + $PROC_CORE)
      set $vt = *(unsigned char*)($proc + $PROC_VT)
      set $uid = *(unsigned short*)($proc + $PROC_UID)
      set $ppid = *(unsigned int*)($proc + $PROC_PARENT)
      set $rip = *(unsigned long long*)($proc + $PROC_USER_RIP)
      set $sn = "?"
      if $st == $STATE_RUNNING
        set $sn = "running"
      end
      if $st == $STATE_READY
        set $sn = "ready"
      end
      if $st == $STATE_BLOCKED
        set $sn = "blocked"
      end
      if $st == $STATE_ZOMBIE
        set $sn = "zombie"
      end
      if $st == $STATE_DEAD
        set $sn = "dead"
      end
      printf "%4d  %-8s  %4d  %2d  %3d  %6d  0x%lx\n", $pid, $sn, $core, $vt, $uid, $ppid, $rip
    end
    set $i = $i + 1
  end
end

define fornax-proc
  if $argc != 1
    printf "Usage: fornax-proc PID\n"
  else
    set $target = $arg0
    set $found = 0
    set $i = 0
    while $i < $MAX_PROCESSES
      set $proc = ($d_processes + $koff) + ($i * $PROC_SIZE)
      set $pid = *(unsigned int*)($proc + $PROC_PID)
      set $st = *(unsigned char*)($proc + $PROC_STATE)
      if $pid == $target && $st != $STATE_FREE
        printf "Process %d (table index %d, @ 0x%lx):\n", $pid, $i, $proc
        printf "  state:       %d\n", $st
        printf "  core:        %d\n", *(unsigned char*)($proc + $PROC_CORE)
        printf "  affinity:    %d\n", *(short*)($proc + $PROC_AFFINITY)
        printf "  vt:          %d\n", *(unsigned char*)($proc + $PROC_VT)
        printf "  uid:         %d\n", *(unsigned short*)($proc + $PROC_UID)
        printf "  parent_pid:  %d\n", *(unsigned int*)($proc + $PROC_PARENT)
        printf "  user_rip:    0x%lx\n", *(unsigned long long*)($proc + $PROC_USER_RIP)
        printf "  user_rsp:    0x%lx\n", *(unsigned long long*)($proc + $PROC_USER_RSP)
        printf "  name:        "
        # Print 16 bytes of name field as chars
        set $j = 0
        while $j < 16
          set $ch = *(unsigned char*)($proc + $PROC_NAME + $j)
          if $ch >= 32 && $ch < 127
            printf "%c", $ch
          end
          set $j = $j + 1
        end
        printf "\n"
        set $found = 1
      end
      set $i = $i + 1
    end
    if !$found
      printf "Process %d not found\n", $target
    end
  end
end

# ── Run queue inspection ─────────────────────────────────────────────

define fornax-runq
  if $koff == 0
    printf "Warning: $koff not set.\n"
  end
  printf "Core  Len  Lock(next/serving)  Head PIDs\n"
  printf "----  ---  ------------------  ---------\n"
  set $i = 0
  while $i < $MAX_CORES
    set $pc_base = ($d_percpu_array + $koff) + ($i * $PERCPU_SIZE)
    set $online = *(unsigned char*)($pc_base + $PC_ONLINE)
    if $online
      set $rq = $pc_base + $PC_RUN_QUEUE
      set $len = *(unsigned int*)($rq + $RQ_LEN)
      set $head = *(unsigned int*)($rq + $RQ_HEAD)
      set $lk_n = *(unsigned int*)($rq + $RQ_LOCK + $SL_NEXT)
      set $lk_s = *(unsigned int*)($rq + $RQ_LOCK + $SL_SERVING)
      set $contended = ""
      if $lk_n != $lk_s
        set $contended = " CONTENDED!"
      end
      printf "  %2d  %3d  %d/%d%s  ", $i, $len, $lk_n, $lk_s, $contended
      set $j = 0
      while $j < $len && $j < 8
        set $idx = ($head + $j) % 64
        set $entry = *(unsigned short*)($rq + $RQ_ENTRIES + $idx * 2)
        printf "%d ", $entry
        set $j = $j + 1
      end
      if $len > 8
        printf "..."
      end
      printf "\n"
    end
    set $i = $i + 1
  end
end

# ── Spinlock inspection ──────────────────────────────────────────────

define fornax-locks
  if $koff == 0
    printf "Warning: $koff not set.\n"
  end
  printf "Checking spinlocks...\n"
  # Process table lock
  set $tl = $d_table_lock + $koff
  set $n = *(unsigned int*)($tl + $SL_NEXT)
  set $s = *(unsigned int*)($tl + $SL_SERVING)
  set $o = *(signed char*)($tl + $SL_OWNER)
  if $n != $s
    printf "  table_lock: CONTENDED (next=%d, serving=%d, owner=core %d)\n", $n, $s, $o
  else
    printf "  table_lock: ok (ticket=%d)\n", $n
  end
  # Per-core run queue locks
  set $i = 0
  while $i < $MAX_CORES
    set $pc_base = ($d_percpu_array + $koff) + ($i * $PERCPU_SIZE)
    set $online = *(unsigned char*)($pc_base + $PC_ONLINE)
    if $online
      set $rql = $pc_base + $PC_RUN_QUEUE + $RQ_LOCK
      set $rn = *(unsigned int*)($rql + $SL_NEXT)
      set $rs = *(unsigned int*)($rql + $SL_SERVING)
      if $rn != $rs
        set $ro = *(signed char*)($rql + $SL_OWNER)
        printf "  core %d runq.lock: CONTENDED (next=%d, serving=%d, owner=%d)\n", $i, $rn, $rs, $ro
      end
    end
    set $i = $i + 1
  end
  printf "Done.\n"
end

# ── AsmState / GS_BASE ──────────────────────────────────────────────

define fornax-gs
  if $koff == 0
    printf "Warning: $koff not set.\n"
  end
  printf "AsmState array at 0x%lx (40 bytes each)\n", ($d_asm_states + $koff)
  printf "Fields: kernel_stack_top | saved_user_rsp | saved_user_rip | saved_user_rflags | saved_kernel_rsp\n\n"
  set $cores = *(unsigned char*)($d_cores_online + $koff)
  set $i = 0
  while $i < $cores
    printf "Core %d: ", $i
    x/5gx ($d_asm_states + $koff) + ($i * 40)
    set $i = $i + 1
  end
end

# ── Backtrace ────────────────────────────────────────────────────────

define fornax-bt-all
  thread apply all bt
end

# ── Breakpoints / watchpoints ────────────────────────────────────────

define fornax-bp
  if $argc != 1
    printf "Usage: fornax-bp $fn_NAME\n"
    printf "  Example: fornax-bp $fn_markReady\n"
    printf "  Example: fornax-bp $fn_scheduleNext\n"
    printf "  Example: fornax-bp $fn_sysExit\n"
  else
    break *($arg0 + $koff)
  end
end

define fornax-watch
  if $argc != 1
    printf "Usage: fornax-watch EXPR\n"
    printf "  Sets a hardware write watchpoint.\n"
    printf "  Examples:\n"
    printf "    fornax-watch ($d_table_lock+$koff)     Watch table_lock.next (u32)\n"
    printf "    fornax-watch ($d_cores_online+$koff)   Watch cores_online (u8)\n"
    printf "  For a specific process state field:\n"
    printf "    set $p = ($d_processes+$koff) + (INDEX * $PROC_SIZE) + $PROC_STATE\n"
    printf "    watch *(char*)$p\n"
  else
    watch *(unsigned int*)$arg0
    printf "Hardware watchpoint set.\n"
  end
end

define fornax-disas
  if $argc != 1
    printf "Usage: fornax-disas $fn_NAME\n"
    printf "  Example: fornax-disas $fn_markReady\n"
  else
    x/60i ($arg0 + $koff)
  end
end

# ── Watch a specific process state transition ────────────────────────

define fornax-watch-proc
  if $argc != 1
    printf "Usage: fornax-watch-proc TABLE_INDEX\n"
    printf "  Sets a hardware watchpoint on the process's state field.\n"
    printf "  Get the index from fornax-procs output or use PID-1 as approximation.\n"
  else
    set $wp_addr = ($d_processes + $koff) + ($arg0 * $PROC_SIZE) + $PROC_STATE
    watch *(unsigned char*)$wp_addr
    printf "Watching process[%d].state at 0x%lx\n", $arg0, $wp_addr
  end
end

# ── Startup message ──────────────────────────────────────────────────

printf "\n"
printf "=== Fornax Kernel Debugger ===\n"
printf "Connected to QEMU GDB stub on :1234\n"
printf "\n"
printf "Quick start:\n"
printf "  1. Type 'continue' to let the kernel boot\n"
printf "  2. Press Ctrl+C to break into the debugger\n"
printf "  3. Run 'fornax-calibrate' to find the kernel load offset\n"
printf "  4. Type 'fornax-help' for all commands\n"
printf "\n"
