#!/usr/bin/env bash
# gen-gdb-syms.sh — Extract symbols from BOOTX64.pdb and generate GDB commands.
#
# Generates fornax-syms.gdb with:
#   - All function symbols (as GDB convenience variables + symbol breakpoint helpers)
#   - All global data symbols (as GDB convenience variables)
#   - Addresses are relative to PE ImageBase (add UEFI relocation offset)
#
# Usage: ./scripts/gen-gdb-syms.sh
# Output: fornax-syms.gdb (sourced by fornax.gdb)

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PDB="$PROJECT_DIR/zig-out/esp/EFI/BOOT/BOOTX64.pdb"
EFI="$PROJECT_DIR/zig-out/esp/EFI/BOOT/BOOTX64.EFI"
OUT="$PROJECT_DIR/fornax-syms.gdb"

if [ ! -f "$PDB" ]; then
    echo "Error: $PDB not found. Build first with: make x86_64"
    exit 1
fi

if ! command -v llvm-pdbutil &>/dev/null; then
    echo "Error: llvm-pdbutil not found. Install llvm tools."
    exit 1
fi

# Get section base addresses from the PE headers
TEXT_VMA=$(objdump -h "$EFI" 2>/dev/null | awk '/\.text/{print "0x"$4}')
DATA_VMA=$(objdump -h "$EFI" 2>/dev/null | awk '/\.data/{print "0x"$4}')

if [ -z "$TEXT_VMA" ] || [ -z "$DATA_VMA" ]; then
    echo "Error: Could not parse PE section headers"
    exit 1
fi

echo "# fornax-syms.gdb — Auto-generated by scripts/gen-gdb-syms.sh" > "$OUT"
echo "# Regenerate with: ./scripts/gen-gdb-syms.sh" >> "$OUT"
echo "#" >> "$OUT"
echo "# PE sections: .text=$TEXT_VMA .data=$DATA_VMA" >> "$OUT"
echo "# All addresses are PE-relative (ImageBase=0)." >> "$OUT"
echo "# After UEFI loads the binary, add the relocation offset:" >> "$OUT"
echo "#   set \$koff = 0x<uefi_load_addr>" >> "$OUT"
echo "#" >> "$OUT"
echo "" >> "$OUT"

# Offset variable (user sets this after finding UEFI load address)
echo "# UEFI relocation offset — set this after finding where OVMF loaded the kernel." >> "$OUT"
echo "# Method: break on 'apEntry' (has known PE address), compare expected vs actual RIP." >> "$OUT"
echo "# Or: add klog.infoHex(@intFromPtr(&main)) to early boot." >> "$OUT"
echo 'if !$koff' >> "$OUT"
echo '  set $koff = 0' >> "$OUT"
echo 'end' >> "$OUT"
echo "" >> "$OUT"

FUNC_COUNT=0
DATA_COUNT=0

# Extract function symbols from module 1 (kernel compilation unit)
echo "# ── Function symbols ──────────────────────────────────────────────" >> "$OUT"
cur_name=""
while IFS= read -r line; do
    # Parse: "  OFFSET | S_LPROC32 [size = N] `name`"
    #        "          parent = ..., addr = SSSS:OFFSET, code size = N"
    if [[ "$line" =~ S_LPROC32.*\`([^\`]+)\` ]]; then
        cur_name="${BASH_REMATCH[1]}"
    elif [[ "$line" =~ addr\ =\ ([0-9]+):([0-9]+),\ code\ size ]] && [ -n "$cur_name" ]; then
        section="${BASH_REMATCH[1]}"
        offset="${BASH_REMATCH[2]}"
        if [ "$section" = "0001" ]; then
            addr=$(printf "0x%x" $(( $TEXT_VMA + $offset )))
        elif [ "$section" = "0002" ]; then
            addr=$(printf "0x%x" $(( $DATA_VMA + $offset )))
        else
            cur_name=""
            continue
        fi
        # Sanitize name for GDB variable (replace . with _)
        varname=$(echo "$cur_name" | tr '.' '_' | tr '-' '_')
        echo "set \$fn_${varname} = $addr" >> "$OUT"
        FUNC_COUNT=$((FUNC_COUNT + 1))
        cur_name=""
    else
        # Reset name if we see an addr line without a name
        if [[ "$line" =~ addr\ = ]]; then
            cur_name=""
        fi
    fi
done < <(llvm-pdbutil dump --symbols --modi=1 "$PDB" 2>/dev/null | grep -E "S_LPROC32.*\`|addr = .*, code size")

echo "" >> "$OUT"

# Extract global data symbols
echo "# ── Data symbols ───────────────────────────────────────────────────" >> "$OUT"
while IFS= read -r line; do
    # Parse: "  OFFSET | S_LDATA32 [size = N] `name`"
    #        "          type = ..., addr = SSSS:OFFSET"
    if [[ "$line" =~ S_LDATA32.*\`([^\`]+)\` ]]; then
        name="${BASH_REMATCH[1]}"
    elif [[ "$line" =~ addr\ =\ ([0-9]+):([0-9]+) ]] && [ -n "${name:-}" ]; then
        section="${BASH_REMATCH[1]}"
        offset="${BASH_REMATCH[2]}"
        if [ "$section" = "0002" ]; then
            addr=$(printf "0x%x" $(( $DATA_VMA + $offset )))
        elif [ "$section" = "0001" ]; then
            addr=$(printf "0x%x" $(( $TEXT_VMA + $offset )))
        elif [ "$section" = "0000" ]; then
            # BSS or absolute — skip the _fltused sentinel
            unset name
            continue
        else
            unset name
            continue
        fi
        varname=$(echo "$name" | tr '.' '_' | tr '-' '_')
        echo "set \$d_${varname} = $addr" >> "$OUT"
        DATA_COUNT=$((DATA_COUNT + 1))
        unset name
    fi
done < <(llvm-pdbutil dump --globals "$PDB" 2>/dev/null | grep -E "S_LDATA32.*\`|type = .*, addr =")

echo "" >> "$OUT"

# Add helper to apply offset
cat >> "$OUT" << 'GDBEOF'
# ── Offset helpers ───────────────────────────────────────────────────
# After finding $koff, use these to get actual runtime addresses:
#   p/x $fn_markReady + $koff      — address of markReady()
#   break *($fn_main + $koff)      — breakpoint on main()
#   x/20i $fn_switchTo + $koff     — disassemble switchTo()
#   x/gx $d_processes + $koff      — examine processes array

define fornax-sym
  if $argc != 1
    printf "Usage: fornax-sym <name>\n"
    printf "  Looks up a symbol by substring. Prefix: $fn_ for functions, $d_ for data.\n"
    printf "  Example: fornax-sym markReady\n"
  else
    printf "Search for convenience variables matching '%s':\n", $arg0
    info variables $arg0
  end
end

define fornax-offset
  if $argc != 1
    printf "Usage: fornax-offset 0xADDRESS\n"
    printf "  Set the UEFI kernel relocation offset.\n"
    printf "  Find it by comparing actual RIP at a known point vs PE address.\n"
    printf "\n"
    printf "Quick method:\n"
    printf "  1. Let kernel boot to serial output\n"
    printf "  2. Ctrl+C in GDB, check 'info threads' for core 0\n"
    printf "  3. Note the current RIP range\n"
    printf "  4. The .text section starts at 0x1000 in the PE\n"
    printf "  5. offset = (actual .text start) - 0x1000\n"
  else
    set $koff = $arg0
    printf "Kernel offset set to "
    output/x $koff
    printf "\nExample: break *($fn_markReady + $koff)\n"
  end
end

define fornax-bp
  if $argc != 1
    printf "Usage: fornax-bp <fn_variable>\n"
    printf "  Set breakpoint on a function using the auto-generated symbol.\n"
    printf "  Example: fornax-bp $fn_markReady\n"
  else
    break *($arg0 + $koff)
  end
end
GDBEOF

echo "==> Generated $OUT with $FUNC_COUNT functions, $DATA_COUNT data symbols"
